# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: K9sAlpha - Manage Your Kubernetes Clusters In Style
email: fernand@k9salpha.io
description: >- # this means to ignore newlines until "baseurl:"
  K9sAlpha provides a terminal UI to interact with your Kubernetes clusters.
  The aim of this project is to make it easier to navigate, observe and manage
  your Kubernetes applications in the wild. K9s𝞪continually watches Kubernetes
  for changes and offers subsequent commands to interact with your observed resources.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://k9salpha.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter: kitesurfer
github: imhotepio/k9salpha

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

collections:
  topics:
    output: true
    permalink: /topics/:path/
